name             'jenkins_server'
maintainer       'The Authors'
maintainer_email 'you@example.com'
license          'all_rights'
description      'Installs/Configures jenkins_server'
long_description 'Installs/Configures jenkins_server'
version          '0.1.0'

depends 'apt', '~> 2.6.1'
depends 'java', '~> 1.31.0'
depends 'jenkins', '~> 2.2.2'
