default['subversion']['repo_dir'] = '/srv/svn'
default['subversion']['repo_name'] = 'repo'
default['subversion']['server_name'] = 'svn'
default['subversion']['user'] = 'subversion'
default['subversion']['password'] = 'subversion'
default['subversion']['list_parent_path'] = 'off'
